rapport.pdf: rapport.tex
	pdflatex rapport.tex

poster.pdf: poster.tex
	pdflatex poster.tex	

clear: 
	rm rapport.pdf rapport.log rapport.toc rapport.aux

clean:
	rm rapport.log rapport.toc rapport.aux